---
title: "R Notebook"
output: html_notebook
---

#Functions for running common analyses


```{r}
#Create metadata and DESeq2 object, then run DESeq2

RunDESeq2<- function(counts,meta, collapseRep=TRUE) {
  #create DESeq2 object- just based on samplegroup (blockerstatus)
  #will add samples to model later (i.e., pairwise analysis)
  dds<- DESeqDataSetFromMatrix(countData=counts, 
                               colData=meta, 
                               design=~sampleGroup)
  #Collapse technical replicates using internal DESeq2 function
  if (collapseRep ==TRUE){
    dds<- collapseReplicates(dds, dds$sample)
  }
  
  #Create model that takes into account sample differences
  ddsMF<- dds
  design(ddsMF)<- formula(~patient + sampleGroup)
  
  #run DESeq2
  dds<- DESeq(ddsMF)
  
  return(dds)
}

#Get DE results
GetDEResults<- function(dds){
  res<- results(dds)
  res<- na.omit(res)
  resOrdered<- res[order(res$padj),]
  print(nrow(resOrdered[resOrdered$padj<0.05,]))
  print(nrow(resOrdered[resOrdered$padj<0.01,]))
  return(resOrdered)
}
  

#Create PCA plot

MyPCA<- function(dds, metadata, PC1Variance, PC2Variance, colors=colors, miny, maxy) {
  #Normalized (variance stabilized transformation), then run PCA
  vsd <- varianceStabilizingTransformation(dds, blind=TRUE)
  PCA<-plotPCA(vsd, intgroup="sampleGroup",returnData=TRUE)
  PCA$Sample<- metadata$Sample
  
  #plot
  p<- ggplot(PCA, aes(x=PC1, y=PC2, color=group))+
  geom_point(size=5)+
  scale_color_manual(values=colors)+
  theme_classic()+
  ylim(miny,maxy)+
  ylab(paste("PC2: ", PC2Variance, "% Variance", sep =""))+
  xlab(paste("PC1: ", PC1Variance, "% Variance", sep =""))+
  geom_text(aes(label=Sample),hjust=.5, size= 5,vjust=-1.2, color="black")+
  theme(axis.text.y   = element_text(size=10, colour = "black"),
        axis.title.y  = element_text(size=14, colour = "black"),
        axis.title.x  = element_text(size=14, colour = "black"),
        axis.text.x  = element_text(size=10, colour = "black"),
        legend.background = element_rect(fill=NA, size=1, 
                                         linetype="solid", color="black"),
        legend.title=element_blank(),
        legend.key.size = unit(.4, "cm"),
        legend.spacing.y = unit(0, "mm"),
        legend.position = c(.9,.892),
        panel.border = element_rect(colour = "black", fill=NA, size=2))
  return(p)
}


#Plot heatmap: takes as input DE results (padj ordered lowest to highest, rlog transformed data, metadata (blocker status and Sample type), number of miRNA species to be included, and min and max subtract (used for heatmap aesthetics))

PlotHeatmap<- function(OrderedResults, rld, metadata, nspecies, MinSubtract, MaxSubtract, fontsize){
  #Select top sig DE miRNAs
  topgenes<- rownames(OrderedResults[1:nspecies,])
  mat<- assay(rld)[topgenes,]
  mat<- mat - rowMeans(mat)
  colnames(mat)<-paste(metadata$Sample," (",metadata$sampleGroup, ")",sep="")
  
  #Heatmap settings
  mat_breaks<- seq(min(mat-MinSubtract), max(mat-MaxSubtract), length.out=75)

  #Create metadata- to be used to color code to show which group the sample belongs to
  metadata<- data.frame(Group=metadata$sampleGroup, 
                        row.names=paste(metadata$Sample," (",metadata$sampleGroup, ")",sep=""),
                        Sample=metadata$Sample)

  #plot heatmap
  p<-pheatmap(mat, breaks = mat_breaks, 
            color =colorRampPalette( c("red", "black", "green"), space="rgb")(100),
            show_rownames = TRUE, show_colnames=FALSE,
            annotation = metadata,  
            annotation_colors= list(
              Group=c(Blocked="firebrick3", Unblocked="blue3"),
                      Sample=c(A="goldenrod1", 
                               B="violetred3", 
                               C="skyblue3", 
                               D="darkolivegreen4")),
            fontsize_row = fontsize,fontsize=12,treeheight_row=0,
            border_color= NA)
  return(p)
}


#Plot log of cpm of raw counts- coloring based on whether it's differentially expressed
CPMPlot<- function(CPM, Sample){
  pA<- ggplot(CPM, aes(x=NoBlocker, y=Blocker, color=Color))+
  geom_point()+
  geom_abline(slope=1, color="red")+
  scale_colour_manual(values=c("red","black", "blue"))+
  theme_classic()+
  xlab(paste("Log of Unblocked Counts Per Million: Sample ", Sample, sep =""))+
  ylab(paste("Log of Unblocked Counts Per Million: Sample ", Sample, sep =""))+
  theme(axis.text.y   = element_text(size=10, colour = "black"),
        axis.title.y  = element_text(size=14, colour = "black"),
        axis.title.x  = element_text(size=14, colour = "black"),
        axis.text.x  = element_text(size=10, colour = "black"),
        legend.background = element_rect(fill=NA, size=1, 
                                         linetype="solid", color="black"),
        legend.title=element_blank(),
        legend.key.size = unit(.4, "cm"),
        legend.spacing.y = unit(0, "mm"),
        legend.position = c(.15,.892),
        panel.border = element_rect(colour = "black", fill=NA, size=2))
return (pA)  
}

```


Variation on the PCA function for adding outline to points
```{r}
vsd <- varianceStabilizingTransformation(dds_TNC, blind=TRUE)
  PCA<-plotPCA(vsd, intgroup="sampleGroup",returnData=TRUE)
  PCA$Sample<- meta$patient
  
  #plot
  p<- ggplot(PCA, aes(x=PC1, y=PC2))+
    geom_point(aes(color=group, fill=Sample), shape=21,size=5,stroke=1.5)+
  scale_color_manual(values=Groupcolors)+
    scale_fill_manual(values=Samplecolors)+
    guides(fill = guide_legend(override.aes = list(color = Samplecolors)),
       color = guide_legend(override.aes = list(shape = 21)))+
  theme_classic()+
  ylim(miny,maxy)+
  ylab(paste("PC2: ", PC2Variance, "% Variance", sep =""))+
  xlab(paste("PC1: ", PC1Variance, "% Variance", sep =""))+
  geom_text(aes(label=Sample),hjust=.5, size= 5,vjust=-1.2, color="black")+
  theme(axis.text.y   = element_text(size=10, colour = "black"),
        axis.title.y  = element_text(size=14, colour = "black"),
        axis.title.x  = element_text(size=14, colour = "black"),
        axis.text.x  = element_text(size=10, colour = "black"),
        legend.background = element_rect(fill=NA, size=1, 
                                         linetype="solid", color="black"),
        legend.title=element_blank(),
        legend.key.size = unit(.4, "cm"),
        legend.spacing.y = unit(0, "mm"),
        legend.position = c(.9,.892),
        panel.border = element_rect(colour = "black", fill=NA, size=2))
```

