---
title: "R Notebook"
output: html_notebook
---

#Rank sum analysis

#Option 1: samples combined, CPM for blocked and unblocked
```{r}
#calculate cpm
cpm<- counts/colSums(counts) * 1000000

#Collapse into two groups: blocked and unblocked
TopSpecies<-cpm
TopSpecies$Unblocked<- rowMeans(TopSpecies[,1:8])
TopSpecies$Blocked<- rowMeans(TopSpecies[,9:16])

##Select just the top 20 Unblocked species
TopSpecies<- TopSpecies[order(TopSpecies$Unblocked, decreasing=TRUE),]
TopSpecies<- TopSpecies[1:20, 17:18]


#calculate Percentage of total reads- will be secondary y axis on plot
Unblocked_Top<- rowMeans(counts[rownames(counts) %in% rownames(TopSpecies), 1:8])
Unblocked_percentage<-as.data.frame(Unblocked_Top/mean(colSums(counts[,1:8]))*100)
Unblocked_percentage$species<- rownames(Unblocked_percentage)
colnames(Unblocked_percentage)<- c("Unblocked_Per", "species")
Unblocked_percentage[21,]<- c(100-sum(Unblocked_percentage[,1]), "AllOthers")

blocked_Top<- rowMeans(counts[rownames(counts) %in% rownames(TopSpecies), 9:16])
blocked_percentage<-as.data.frame(blocked_Top/mean(colSums(counts[,9:16]))*100)
blocked_percentage$species<- rownames(blocked_percentage)
colnames(blocked_percentage)<- c("blocked_Per", "species")
blocked_percentage[21,]<- c(100-sum(blocked_percentage[,1]), "AllOthers")

#Calculate CPM for all other species not in top 20 (from percentage)
TopSpecies[21,]<- c(as.numeric(Unblocked_percentage[21,1])*10000, 
                    as.numeric(blocked_percentage[21,1]) * 10000)
rownames(TopSpecies)<- c(rownames(TopSpecies[1:20,]), "AllOthers")
TopSpecies$species<- rownames(TopSpecies)

#Merge with CPM for 5 total colums: species/unblocked cpm/blocked cpm/ unblocked percentage/blocked percentage
merging<-merge(TopSpecies, Unblocked_percentage, by="species")
TopSpecies_Final<-merge(merging, blocked_percentage, by="species")
AllOthers<-TopSpecies_Final[grep("AllOthers", TopSpecies_Final$species),]
TopSpecies_Final<- TopSpecies_Final[-1,]
TopSpecies_Final<- TopSpecies_Final[order(TopSpecies_Final$Unblocked, decreasing=TRUE),]
TopSpecies_Final<- rbind(TopSpecies_Final, AllOthers)

#Reformat for plotting
TopSpecies_melt<- melt(TopSpecies_Final, id="species")
TopSpecies_Plot<- cbind(TopSpecies_melt[1:42,], TopSpecies_melt[43:84,])
TopSpecies_Plot<-TopSpecies_Plot[,c(1,2,3,6)]
colnames(TopSpecies_Plot)<- c("species", "BlockerStatus", "CPM", "Percentage")
TopSpecies_Plot$SpeciesOrder<- rep(1:21,2)
TopSpecies_Plot$StatusOrder<- c(rep(1,21), rep(2,21))
TopSpecies_Plot$CPM<- as.integer(TopSpecies_Plot$CPM)

SecAxisBreaks<-seq(0,60, by=10)
SecAxisLabels<-paste(seq(0,60,by=10), "%", sep="")
YaxisLimits<-c(0,600000)
YaxisBreaks<-seq(0,600000, by=100000)
YaxisLabels<-c("0", "100,000", "200,000", "300,000", "400,000", "500,000", "600,000")


PlotRankSum<- function(df,SecAxisBreaks=SecAxisBreaks,SecAxisLabels=SecAxisLabels,YaxisLimits=YaxisLimits,YaxisBreaks=YaxisBreaks,YaxisLabels=YaxisLabels){
        p<-ggplot(df, aes(x=reorder(species, + SpeciesOrder), 
                                y=CPM,
                                group=StatusOrder,
                                fill=factor(BlockerStatus, levels=c("Blocked", "Unblocked"))))+
        geom_bar( stat="identity",width= .8, position=position_dodge(width = 0.7))+
        theme_classic()+
        xlab("")+
        scale_y_continuous(name = "Counts Per Million",
                           sec.axis = sec_axis( trans=~.*.0001, 
                                                name="Percentage of Total Reads", 
                                                breaks=seq(0,60, by=10),
                                                labels=paste(seq(0,60,by=10), "%", sep="")),
                           limits=c(0,600000),
                           breaks=seq(0,600000, by=100000) ,
                           labels=c("0", "100,000", "200,000", "300,000", "400,000", "500,000", "600,000"))+
        scale_fill_manual("", values=c("Blocked"="firebrick3", "Unblocked"="turquoise3"))+
        theme(axis.text.y   = element_text(size=14, colour = "black", face="bold"),
                axis.title.y  = element_text(size=11, colour = "black", face="bold"),
                axis.text.x  = element_text(size=14, colour = "black", face="bold", angle=45, hjust=1),
                legend.background = element_rect(fill=NA, size=1, 
                                         linetype="solid", color="black"),
                legend.title=element_blank(),
                legend.key.size = unit(.4, "cm"),
                legend.spacing.y = unit(0, "mm"),
                legend.position = c(.84,.8),
                legend.text = element_text(size=12, face="bold"),
                panel.border = element_rect(colour = "black", fill=NA, size=2))
        return(p)
        
        
}

PlotRankSum(TopSpecies_Plot)
```


Alternative plotting:
#Option 2: Top 20, mean across blocked/unblocked libraries, split by sample
```{r}
#Collapse technical replicates for A and B
cpm$A.0<- rowMeans(cpm[,1:3])
cpm$B.0<- rowMeans(cpm[,4:6])
cpm$A.1<- rowMeans(cpm[,9:11])
cpm$B.1<- rowMeans(cpm[,12:14])
cpm<- cpm[,c(17,18,7,8,19,20,15,16)]

#split into 4 dataframes
CPM_Samples<- list(cpm[,c(1,5)], cpm[,c(2,6)], cpm[,c(3,7)], cpm[,c(4,8)])

#Get top n species in unblocked libraries in all 4 samples
Topn<-20
CPM_Top20<- lapply(CPM_Samples, function(x) {x[order(x[,1], decreasing=TRUE),]})
CPM_Top20<- lapply(CPM_Top20, function(x){x[1:Topn,]})

#Get number of CPM for all species not in top 20 
CPM_Top20_AllOthers<- list()
for (i in 1:length(CPM_Top20)){
        df<- CPM_Top20[[i]]
        miRs<- rownames(df)
        total<- colSums(df)
        df[Topn+1,]<- 1000000-total
        rownames(df)<- c(miRs, "AllOthers")
        colnames(df)<- c("Unblocked", "Blocked")
        df$species<-rownames(df)
        CPM_Top20_AllOthers[[i]]<-df
        
}

#Melt dataframes for plotting
CPM_Top20_Melt<- lapply(CPM_Top20_AllOthers, melt)

#Add columns for ordering graph
plot_df<-list()
for (i in 1:length(CPM_Top20_Melt)){
     df<- CPM_Top20_Melt[[i]]
     colnames(df)<- c("species", "BlockerStatus", "CPM")
     df$SpeciesOrder<- rep(1:(Topn + 1),2)
     df$StatusOrder<-  c(rep(1,(Topn + 1)), rep(2,(Topn+1)))
     plot_df[[i]]<-df
}


p<-PlotRankSum(plot_df[[1]])

grid.arrange((PlotRankSum(plot_df[[1]])+ggtitle("SampleA")), 
             (PlotRankSum(plot_df[[2]])+ggtitle("SampleB")),
             (PlotRankSum(plot_df[[3]])+ggtitle("SampleC")), 
             (PlotRankSum(plot_df[[4]])+ggtitle("SampleD")),nrow=2)

```

#Option 3: Top 20, Blocked CPM minus unblocked CPM, split by sample


```{r}
#To top 20 CPMs split by sample, add column for subtracting blocked-unblocked CPMs
CPM_BminusUB<-list()
for (i in 1:length(CPM_Top20_AllOthers)){
        df<-CPM_Top20_AllOthers[[i]]
        df$UnblockedMinusBlocked<- df$Blocked-df$Unblocked
        CPM_BminusUB[[i]]<-df[,3:4]
}

#Melt dataframes for plotting
CPM_BminusUB_melt<- lapply(CPM_BminusUB, melt)

#Add columns for ordering graph
plot_df_BminusUB<-list()
for (i in 1:length(CPM_BminusUB_melt)){
     df<- CPM_BminusUB_melt[[i]]
     colnames(df)<- c("species", "BlockerStatus", "CPM")
     df$SpeciesOrder<- rep(1:(Topn + 1),1)
     df$StatusOrder<-  c(rep(1,(Topn + 1)))
     df$BlockerStatus<- rep("Blocked", nrow(df))
     plot_df_BminusUB[[i]]<-df
}

#Edit previous function for plotting
New_PlotRankSum<-function(df,title){
        PlotRankSum(df)+  
        ylim(-450000,350000)+
        scale_y_continuous(breaks=seq(-400000,200000, by=100000), 
                           labels=c("-400,000", "-300,000","-200,000","-100,000", 0,"100,000", "200,000"))+
        ylab("CPM Blocked Libraries \n minus CPM Unblocked libraries")+
        geom_hline(yintercept=0,size=1)+
        ggtitle(title)+
        theme(axis.text.y=element_text(size=11),
              axis.text.x=element_text(size=8),
              legend.position="none",
              plot.title = element_text(size=13, face="bold"))
}

#Plot all samples- this version used, exported as Figure2BAlternative_SplitBySample_BlockedMinusUnblocked
grid.arrange(New_PlotRankSum(plot_df_BminusUB[[1]], "Sample A"),
             New_PlotRankSum(plot_df_BminusUB[[2]], "Sample B"),
             New_PlotRankSum(plot_df_BminusUB[[3]], "Sample C"),
             New_PlotRankSum(plot_df_BminusUB[[4]], "Sample D"),
             nrow=2)

```

#Option 3: Top 20, %change in blocked CPMs, split by sample.Targets/25-3p not included


```{r}
#To top 20 CPMs split by sample, add column for taking blocked percentage of unblocked
CPM_BPerUB<-list()
for (i in 1:length(CPM_Top20_AllOthers)){
        df<-CPM_Top20_AllOthers[[i]]
        df$BlockedPer<-(df$Blocked-df$Unblocked)/df$Blocked
        CPM_BPerUB[[i]]<-df[,3:4]
}

#Remove rows with negative percentage (targets + 25-3p)
CPM_BPerUB_NoTargets<-lapply(CPM_BPerUB,function(x){x[x$BlockedPer>0,]})

#Melt dataframes for plotting
CPM_BPerUB_melt<- lapply(CPM_BPerUB_NoTargets, melt)

#Add columns for ordering graph
plot_df_BPerUB<-list()
for (i in 1:length(CPM_BPerUB_melt)){
     df<- CPM_BPerUB_melt[[i]]
     colnames(df)<- c("species", "BlockerStatus", "CPM")
     df$SpeciesOrder<- rep(1:(nrow(df)),1)
     df$StatusOrder<-  c(rep(1,(nrow(df))))
     df$BlockerStatus<- rep("Blocked", nrow(df))
     plot_df_BPerUB[[i]]<-df
}


breaks<-seq(0,1,by=.25)
labels<-c("0%", "25%", "50%", "75%", "100%")
yaxis<-"Percent change in CPM \n (Blocked-Unblocked)/Unblocked"
ylim<-c(0,1)
grid.arrange(
    PlotRankSum(plot_df_BPerUB[[1]])+
        ylim(ylim)+
        scale_y_continuous(breaks=breaks, 
                           labels=labels)+
            ylab(yaxis)+
            ggtitle("SampleA")+
            theme(axis.title.y=element_text(size=9),
                  legend.position= 'none'),
    PlotRankSum(plot_df_BPerUB[[2]])+
        ylim(ylim)+
        scale_y_continuous(breaks=breaks, 
                           labels=labels)+
            ylab(yaxis)+
            ggtitle("SampleB")+
            theme(axis.title.y=element_text(size=9),
                  legend.position= 'none'),
    PlotRankSum(plot_df_BPerUB[[3]])+
        ylim(ylim)+
        scale_y_continuous(breaks=breaks, 
                           labels=labels)+
            ylab(yaxis)+
            ggtitle("SampleC")+
            theme(axis.title.y=element_text(size=9),
                  legend.position= 'none'),
    PlotRankSum(plot_df_BPerUB[[4]])+
        ylim(ylim)+
        scale_y_continuous(breaks=breaks, 
                           labels=labels)+
            ylab(yaxis)+
            ggtitle("SampleD")+
            theme(axis.title.y=element_text(size=9),
                  legend.position= 'none'),
    nrow=2
        
)

```

